stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/heart_cleveland_upload.csv
    - src/preprocess.py
    outs:
    - data/processed/test.csv
    - data/processed/training.csv
  tune_hyperparameters:
    cmd: python src/tune.py
    deps:
    - data/processed/test.csv
    - data/processed/training.csv
    - src/tune.py
    outs:
    - results/tuned_hyperparameters.json
