stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/heart_cleveland_upload.csv
    - src/preprocess.py
    outs:
    - data/processed/test.csv
    - data/processed/training.csv
  tune_hyperparameters:
    cmd: python src/tune.py
    deps:
    - data/processed/test.csv
    - data/processed/training.csv
    - src/tune.py
    outs:
    - results/tuned_hyperparameters.json
  train:
    cmd: python src/train.py
    deps:
    - data/processed/training.csv
    - results/tuned_hyperparameters.json
    - src/train.py
    outs:
    - models/logistic_regression.pickle
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/test.csv
    - models/logistic_regression.pickle
    - src/evaluate.py
    plots:
    - results/calibration_curve.json:
        cache: false
    - results/pr_curve.json:
        cache: false
    - results/roc_curve.json:
        cache: false
    metrics:
    - results/scores.json:
        cache: false
